# Generated by Django 5.1.5 on 2025-01-25 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeed', '0004_alter_feed_folder_alter_folder_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_folders', to='rssfeed.folder'),
        ),
    ]
