# Generated by Django 5.1.5 on 2025-01-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeed', '0005_alter_folder_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folder',
            new_name='parent_folder',
        ),
    ]
