# Generated by Django 5.1.5 on 2025-01-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeed', '0006_rename_folder_folder_parent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
