# Generated by Django 5.1.5 on 2025-01-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeed', '0007_folder_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
