# Generated by Django 5.1.5 on 2025-01-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeed', '0008_alter_folder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
